% Fig3.m
%
% Purpose: Plot Figure 3 in Fish to Fight by Yifan Lu and Satoshi Yamazaki
%

clear variables
clc
close all

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 1. READ DATA
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% point estimate
conflict0   = 0.134;
conflict50  = 0.744;
conflict100 = 1.501;
conflict150 = 1.605;
conflict200 = 1.571;

% 95% CIs
LB0 = conflict0-0.067;
UB0 = 0.2-conflict0;
LB50 = conflict50-0.380;
UB50 = 1.108-conflict50;
LB100 = conflict100-0.852;
UB100 = 2.150-conflict100;
LB150 = conflict150-0.873;
UB150 = 2.2385-conflict150;
LB200 = conflict200-0.757;
UB200 = 2.385-conflict200;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 2. PLOT
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% aux line
auxX = [0 1];
auxY = [0 0];

% plot
figure
aLine=plot(auxX,auxY,...
    'LineStyle',':',...
    'Color','k',...
    'LineWidth',2);
hold all
errorbar(0.1,conflict0,LB0,UB0,...
    'LineStyle','none',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','o',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','w')
errorbar(0.3,conflict50,LB50,UB50,...
    'LineStyle','none',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','o',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','w')
errorbar(0.5,conflict100,LB100,UB100,...
    'LineStyle','none',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','o',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','w')
errorbar(0.7,conflict150,LB150,UB150,...
    'LineStyle','none',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','o',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','w')
errorbar(0.9,conflict200,LB200,UB200,...
    'LineStyle','none',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','o',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','w')
xlabel('Search range',...
    'Fontname', 'times new roman','FontSize',16)
ylabel('Coefficient estimate (\beta)',...
    'Fontname', 'times new roman','FontSize',16)
xlim([0,1])
ylim([-0.2,2.6])
set(gca,'XTick',[0.1 0.3 0.5 0.7 0.9],...
        'YTick',[0 0.5 1 1.5 2 2.5],...
        'XTickLabel',{'0 nmi';'50 nmi';'100 nmi';'150 nmi';'200 nmi'},...
        'YTickLabel',{'0';'0.5';'1.0';'1.5';'2.0'},...
        'Fontname', 'times new roman','FontSize',12,...
        'Box','off')
